package calle.david.udacityrecipeapp.UI;


import android.content.pm.ActivityInfo;
import android.support.test.espresso.IdlingRegistry;
import android.support.test.espresso.ViewAction;
import android.support.test.espresso.ViewInteraction;
import android.support.test.filters.LargeTest;
import android.support.test.rule.ActivityTestRule;
import android.support.test.runner.AndroidJUnit4;
import android.view.View;
import android.view.ViewGroup;
import android.view.ViewParent;

import org.hamcrest.Description;
import org.hamcrest.Matcher;
import org.hamcrest.TypeSafeMatcher;
import org.hamcrest.core.IsInstanceOf;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import calle.david.udacityrecipeapp.R;
import calle.david.udacityrecipeapp.Utilities.EspressoIdlingResource;

import static android.support.test.espresso.Espresso.onView;
import static android.support.test.espresso.action.ViewActions.click;
import static android.support.test.espresso.action.ViewActions.scrollTo;
import static android.support.test.espresso.action.ViewActions.swipeDown;
import static android.support.test.espresso.action.ViewActions.swipeUp;
import static android.support.test.espresso.assertion.ViewAssertions.matches;
import static android.support.test.espresso.contrib.RecyclerViewActions.actionOnItemAtPosition;
import static android.support.test.espresso.matcher.ViewMatchers.isDisplayed;
import static android.support.test.espresso.matcher.ViewMatchers.withId;
import static android.support.test.espresso.matcher.ViewMatchers.withText;
import static org.hamcrest.Matchers.allOf;

@LargeTest
@RunWith(AndroidJUnit4.class)
public class UITest {

    @Rule
    public ActivityTestRule<MainActivity> mActivityTestRule = new ActivityTestRule<>(MainActivity.class);
    @Before
    public void setUp() {
        IdlingRegistry.getInstance().register(EspressoIdlingResource.getIdlingResource());
    }

    @Test//automatically generated by recording UI only works on portrait
    public void ClickToDetailsMatchesRecipe() {
        mActivityTestRule.getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);

        ViewInteraction recyclerView = onView(
                allOf(withId(R.id.recipeCardsRV),
                        childAtPosition(
                                withId(R.id.recipe_card_fragment),
                                0)));
        recyclerView.perform(actionOnItemAtPosition(0, click()));

        ViewInteraction scrollView = onView(
                allOf(withId(R.id.ingredients_master_list_fragment),
                        childAtPosition(
                                allOf(withId(R.id.recipe_card_view_fragment),
                                        childAtPosition(
                                                IsInstanceOf.<View>instanceOf(android.widget.RelativeLayout.class),
                                                0)),
                                0),
                        isDisplayed()));
        scrollView.check(matches(isDisplayed()));

        ViewInteraction textView = onView(
                allOf(withId(R.id.ingredients_card_name), withText("Nutella Pie"),
                        childAtPosition(
                                childAtPosition(
                                        withId(R.id.ingredientsCardVew),
                                        0),
                                1),
                        isDisplayed()));
        textView.check(matches(withText("Nutella Pie")));
    }
    @Test//written by me for portrait mode
    public void NavigationPortrait(){
        mActivityTestRule.getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);

        onView(withId(R.id.recipeCardsRV))
                .perform(actionOnItemAtPosition(0,click()));
        onView(withId(R.id.ingredients_master_list_fragment)).check(matches(isDisplayed()));
        onView(withId(R.id.ingredients_master_list_fragment))
                .perform(swipeUp());


        onView(withId(R.id.ingredientsListStepsRV))
                .perform(actionOnItemAtPosition(0,click()));
        onView(withId(R.id.recipe_steps_fragment)).check(matches(isDisplayed()));


    }
    @Test//written by me for landscape
    public void NavigationLandscape(){
        mActivityTestRule.getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);

        onView(withId(R.id.recipeCardsRV))
                .perform(actionOnItemAtPosition(0,click()));
        onView(withId(R.id.ingredients_master_list_fragment)).check(matches(isDisplayed()));
        onView(withId(R.id.ingredients_master_list_fragment))
                .perform(swipeUp());

        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        onView(withId(R.id.ingredientsListRV))
                .check(matches(isDisplayed()));

        onView(withId(R.id.ingredientsListStepsRV))
                .perform(actionOnItemAtPosition(0,click()));
        onView(withId(R.id.fullscreen_video_player_fragment)).check(matches(isDisplayed()));



    }

    private static Matcher<View> childAtPosition(
            final Matcher<View> parentMatcher, final int position) {

        return new TypeSafeMatcher<View>() {
            @Override
            public void describeTo(Description description) {
                description.appendText("Child at position " + position + " in parent ");
                parentMatcher.describeTo(description);
            }

            @Override
            public boolean matchesSafely(View view) {
                ViewParent parent = view.getParent();
                return parent instanceof ViewGroup && parentMatcher.matches(parent)
                        && view.equals(((ViewGroup) parent).getChildAt(position));
            }
        };
    }
}
